import MineField

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 500
SOLDIER_HEIGHT = 80
SOLDIER_WIDTH = 70
VEL = 20
FPS = 60


SCREEN_COLOR = (61, 145, 64)
SCREEN_ENTER_COLOR = (0,0,0)

BUSHES_SIZE = (220, 60)
BUSHES_NUMBER = 20

FLAG_SIZE = (80, 80)

MINE_SIZE = (60, 20)

ROWS = 25
COLUMN = 50
DISTANCE_BTW_ROWS = WINDOW_HEIGHT // ROWS

FINISH = False
MINEFIELD = MineField.creating_minefield()
LIST = MineField.mines_location(MINEFIELD)


FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (0,0,0)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))